<a href="https://colab.research.google.com/github/imrs12/practical/blob/main/7th.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!pip install pandas plotly faker

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: plotly in /usr/local/lib/python3.12/dist-packages (5.24.1)
Collecting faker
  Downloading faker-40.15.0-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.1)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from plotly) (9.1.4)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from plotly) (26.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading faker-40.15.0-py3-none-any.whl (2.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 22.6 MB/s eta 0:00:00
Installing collected packages: faker
Successfully installed faker-40.15.0

In [3]:
import pandas as pd
import random
import plotly.express as px
from faker import Faker

In [4]:
fake = Faker()

sentiments = ['Positive', 'Negative', 'Neutral']
hashtags = ['#AI', '#Tech', '#DataScience', '#Python', '#Startup']

data = []

for i in range(200) :
  post = {
      'user': fake.user_name(),
      'post_text': fake.sentence(),
      'sentiment': random.choice(sentiments),
      'likes': random.randint(10,500),
      'comments': random.randint(1,100),
      'shares': random.randint(1,50),
      'hashtag': random.choice(hashtags)
  }
  data.append(post)

df = pd.DataFrame(data)

df.head()

,user,post_text,sentiment,likes,comments,shares,hashtag
0,mooredawn,Arm include evidence machine usually describe.,Neutral,268,45,7,#Startup
1,frenchashley,Admit young century job cultural discover reme...,Neutral,479,43,43,#DataScience
2,david19,Beyond ahead example increase white.,Negative,214,97,17,#Tech
3,frank03,Person serve teacher story yet.,Negative,262,16,25,#Python
4,lorettahughes,Fund medical hear and growth history get baby.,Neutral,166,79,30,#Tech

In [5]:
df['engagement'] = df['likes'] + df['comments'] + df['shares']

df.head()

,user,post_text,sentiment,likes,comments,shares,hashtag,engagement
0,mooredawn,Arm include evidence machine usually describe.,Neutral,268,45,7,#Startup,320
1,frenchashley,Admit young century job cultural discover reme...,Neutral,479,43,43,#DataScience,565
2,david19,Beyond ahead example increase white.,Negative,214,97,17,#Tech,328
3,frank03,Person serve teacher story yet.,Negative,262,16,25,#Python,303
4,lorettahughes,Fund medical hear and growth history get baby.,Neutral,166,79,30,#Tech,275

In [7]:

sentiment_count = df['sentiment'].value_counts().reset_index()
sentiment_count.columns = ['Sentiment', 'Count']

fig = px.pie(
    sentiment_count,
    values='Count',
    names='Sentiment',
    title="Sentiment Distribution"
)

fig.show()

In [8]:
hashtag_count = df['hashtag'].value_counts().reset_index()
hashtag_count.columns = ["Hashtag", "Count"]

fig = px.bar(
    hashtag_count,
    x= "Hashtag",
    y="Count",
    title="Trending Hashtags"
)

fig.show()

In [10]:
fig = px.scatter(
    df,
    x="likes",
    y="shares",
    color="sentiment",
    size='engagement',
    title="Engagement Analysis"
)

fig.show()

In [11]:
top_posts = df.sort_values(by="engagement", ascending=False).head(10)

top_posts[["user", "post_text", "engagement"]]

,user,post_text,engagement
188,otaylor,Seek right the station young reality.,631
33,melissaboyd,Describe without democratic put appear ready.,621
177,cfranklin,Century color newspaper admit floor.,617
125,shelly48,Reveal sit industry major himself statement bl...,595
171,wberger,Activity themselves theory kid test food class.,592
65,scott69,By detail radio reality law turn.,588
109,bethanysanchez,Operation record each must fact.,586
120,amber17,Issue fish company animal professor central rise.,582
74,nicolemartinez,Hear possible tax take instead she whose.,581
147,benjamin26,Sea cost card article make.,579

In [13]:
report = {
    "Total Posts": len(df),
    "Average Likes": df["likes"].mean(),
    "Average comments": df['comments'].mean(),
    "Average  Shares": df['shares'].mean(),
    "Most Trending Hashtag": df['hashtag'].mode()[0]
}

report

{'Total Posts': 200,
 'Average Likes': np.float64(268.275),
 'Average comments': np.float64(48.275),
 'Average  Shares': np.float64(25.93),
 'Most Trending Hashtag': '#DataScience'}